import { motion, useReducedMotion } from 'motion/react';
import { useI18n } from '../../context/I18nContext';

export default function ParentWeeklyReport({ companion }) {
  const { t } = useI18n();
  const reduceMotion = useReducedMotion();

  const report = companion?.weeklyReport || {};
  const learner = companion?.learner || {};

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="parent-section-container">
      {/* Header */}
      <header className="parent-subview-header">
        <div className="report-header-row">
          <div>
            <span className="parent-badge-kicker">Weekly Digest</span>
            <h2>📅 {t('parent.nav.reports') || 'Weekly Report'}</h2>
            <p className="parent-subview-desc">
              Summary of progress, highlights, and recommended home focus for {report.learnerName || learner.name || 'your learner'}.
            </p>
          </div>
          <button className="parent-outline-btn print-btn" type="button" onClick={handlePrint}>
            🖨️ Print / Save PDF
          </button>
        </div>
      </header>

      {/* Main Weekly Report Card */}
      <motion.div
        className="parent-card weekly-report-card"
        initial={reduceMotion ? false : { opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
      >
        <div className="report-card-topbar">
          <span className="report-date-badge">{report.weekLabel || 'Current Week'}</span>
          <span className="report-learner-tag">Learner: {report.learnerName || learner.name}</span>
        </div>

        {/* 4 Summary Stats */}
        <div className="report-stats-grid">
          <div className="report-stat-box">
            <span className="stat-label">Sessions Completed</span>
            <strong className="stat-number">{report.sessionsCompleted || 0}</strong>
          </div>
          <div className="report-stat-box">
            <span className="stat-label">Total Practice Time</span>
            <strong className="stat-number">{report.totalPracticeTimeMinutes || 0} mins</strong>
          </div>
          <div className="report-stat-box">
            <span className="stat-label">Improvement Trend</span>
            <strong className="stat-number trend-number">{report.improvementTrend || 'Steady'}</strong>
          </div>
          <div className="report-stat-box">
            <span className="stat-label">Active Skills</span>
            <strong className="stat-number">{report.skillsPracticed?.length || 0}</strong>
          </div>
        </div>

        {/* Highlights & Wins */}
        <div className="report-highlights-section">
          <div className="report-highlight-card win-card">
            <div className="highlight-head">
              <span className="hl-icon">🏆</span>
              <strong>Biggest Win This Week</strong>
            </div>
            <p>{report.biggestWin || 'Consistent participation in learning activities.'}</p>
          </div>

          <div className="report-highlight-card focus-card">
            <div className="highlight-head">
              <span className="hl-icon">🎯</span>
              <strong>Recommended Next Focus</strong>
            </div>
            <p>{report.recommendedFocus || 'Starting conversations independently.'}</p>
          </div>

          <div className="report-highlight-card home-card">
            <div className="highlight-head">
              <span className="hl-icon">🏠</span>
              <strong>Home Practice Recommendation</strong>
            </div>
            <p>{report.homePracticeRecommendation || 'Practice a 5-minute greeting roleplay together.'}</p>
          </div>
        </div>

        {/* Skills Practiced List */}
        {report.skillsPracticed?.length > 0 && (
          <div className="report-skills-list-wrap">
            <strong>Skills Practiced:</strong>
            <div className="chips-wrap">
              {report.skillsPracticed.map((skill, idx) => (
                <span key={idx} className="mini-chip">{skill}</span>
              ))}
            </div>
          </div>
        )}

        <div className="report-footer-note">
          <small>Generated by HumSaathi AI Parent Companion · {new Date().toLocaleDateString()}</small>
        </div>
      </motion.div>
    </div>
  );
}
